POST localhost:8080/authenticate
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}


###
GET localhost:8080/books/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg


###
POST localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg
Content-Type: application/json

{
  "name": "nhn",
  "publisher": "cre3wfr",
  "stock": 5
}

###
GET localhost:8080/customers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0ODI1MDM3LCJpYXQiOjE2NDQ3ODkwMzd9.B8s1QB0V-0JrvKcIAQP30WShbDbKxmXw-kpLuQ-LFEA

###
POST localhost:8080/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg
Content-Type: application/json

{
  "name": "amitd",
  "contactNumber": "6576556",
  "email": "abc@gmail.com"
}

###
GET localhost:8080/customers/2/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg

###
GET localhost:8080/orders/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg

###
POST localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg
Content-Type: application/json

{
  "customer_id": 2,
  "books_quantity": [
    {"bookId" : 4, "quantity": 2}
  ],
  "amount": 1000
}

###
GET localhost:8080/orders/interval?fromDate=2022-01-31&toDate=2022-03-01
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg

###
GET localhost:8080/stats/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg

###
GET localhost:8080/stats/customers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NzQwNjQwLCJpYXQiOjE2NDQ3MDQ2NDB9.WFTyNgVHNJJrWnE_PI9NLa9j4nwePdnp3l3aJ04vOSg