spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jackson:
    serialization:
      fail-on-empty-beans: false

springdoc:
  api-docs:
    path: /book-docs
server:
  port: 9090
