POST localhost:8080/authenticate
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}


###
GET localhost:8080/books/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY


###
POST localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY
Content-Type: application/json

{
  "name": "cew",
  "publisher": "cre3wfr",
  "stock": 34
}

###
GET localhost:8080/customers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY

###
POST localhost:8080/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY
Content-Type: application/json

{
  "name": "amit",
  "contactNumber": "6576556",
  "email": "abc@gmail.com"
}

###
GET localhost:8080/customers/2/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY

###
GET localhost:8080/orders/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY

###
POST localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY
Content-Type: application/json

{
  "customer_id": 2,
  "book_ids": [
    1
  ],
  "amount": 13.34
}

###
GET localhost:8080/orders/interval?fromDate=2022-01-31&toDate=2022-03-01
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY

###
GET localhost:8080/stats/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY

###
GET localhost:8080/stats/customers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NjI3MjAxLCJpYXQiOjE2NDQ1OTEyMDF9.Q-iZY9F0-tIrFNDVn4yw7de-6FqMVYhxpxOJkDl1BtY