POST localhost:8080/authenticate
Content-Type: application/json

{
  "username": "test",
  "password": "test"
}


###
GET localhost:8080/books/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NTIxMzcyLCJpYXQiOjE2NDQ0ODUzNzJ9.3NLDFxXEiJleWTI9PwpzAtx1u0wj6Txpx-DgRw3LElU


###
POST localhost:8080/books
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NTIxMzcyLCJpYXQiOjE2NDQ0ODUzNzJ9.3NLDFxXEiJleWTI9PwpzAtx1u0wj6Txpx-DgRw3LElU
Content-Type: application/json

{
  "name": "cew",
  "publisher": "cre3wfr",
  "stock": 34
}

###
GET localhost:8080/customers/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NTIxMzcyLCJpYXQiOjE2NDQ0ODUzNzJ9.3NLDFxXEiJleWTI9PwpzAtx1u0wj6Txpx-DgRw3LElU

###
POST localhost:8080/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NTIxMzcyLCJpYXQiOjE2NDQ0ODUzNzJ9.3NLDFxXEiJleWTI9PwpzAtx1u0wj6Txpx-DgRw3LElU
Content-Type: application/json

{
  "name": "amit",
  "contactNumber": "6576556"
}

###
GET localhost:8080/customers/1/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NTIxMzcyLCJpYXQiOjE2NDQ0ODUzNzJ9.3NLDFxXEiJleWTI9PwpzAtx1u0wj6Txpx-DgRw3LElU

###
GET localhost:8080/orders/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NTIxMzcyLCJpYXQiOjE2NDQ0ODUzNzJ9.3NLDFxXEiJleWTI9PwpzAtx1u0wj6Txpx-DgRw3LElU

###
POST localhost:8080/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiZXhwIjoxNjQ0NTIxMzcyLCJpYXQiOjE2NDQ0ODUzNzJ9.3NLDFxXEiJleWTI9PwpzAtx1u0wj6Txpx-DgRw3LElU
Content-Type: application/json

{
  "customer_id": 2,
  "book_ids": [
    1
  ],
  "amount": 13.34
}